
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('1', 'Wireless Mouse','ELECTRONICS', 29.99, 'PLN')
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('2', 'LCD Monitor 24''','ELECTRONICS', 499.89, 'PLN')
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('3', 'Basic Keyboard','ELECTRONICS', 52.49, 'PLN')
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('4', 'External SSD 512MB','ELECTRONICS', 799.99, 'PLN')
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('5', 'PenDrive 8GB','ELECTRONICS', 39.99, 'PLN')
INSERT INTO PRODUCT(ID, NAME, TYPE, PRICE_VALUE, PRICE_CURRENCY) VALUES('6', 'HiFi 5.1 ','ELECTRONICS', 2099.99, 'PLN')

